DROP DATABASE IF EXISTS CASHINDB;
CREATE DATABASE CASHINDB;
USE CASHINDB;

CREATE TABLE USUARIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20),
    NOMEUSUARIO VARCHAR(20) NOT NULL UNIQUE,
    SENHA VARCHAR(50) NOT NULL,
    DOCUMENTO VARCHAR(20),
    TIPODOCUMENTO VARCHAR(4),
    ENDERECO VARCHAR(100),
    CIDADE VARCHAR(100),
    ESTADO VARCHAR(2),
    CEP VARCHAR(8),
    NOMEFANTASIA VARCHAR(100)	
);

CREATE TABLE CLIENTE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100),
	CONTATO VARCHAR(100),
    DOCUMENTO VARCHAR(20),
    TIPODOCUMENTO VARCHAR(4),
    ENDERECO VARCHAR(100),
    CIDADE VARCHAR(100),
    ESTADO VARCHAR(2),
    CEP VARCHAR(8),
    TELEFONE VARCHAR(20),
    IDUSUARIO INT NOT NULL,
    FOREIGN KEY (IDUSUARIO)
        REFERENCES USUARIO (ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE CLIENTE
ADD COLUMN CONTATO VARCHAR(100);

CREATE TABLE ORCAMENTO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    IDCLIENTE INT NOT NULL,
    IDUSUARIO INT NOT NULL,
	TITULO VARCHAR(100),
	DESCRICAO VARCHAR(400),
	APROVADO BOOL DEFAULT FALSE,
    DATA DATE NOT NULL,
    VALIDADE DATE NOT NULL,
    FOREIGN KEY (IDCLIENTE)
        REFERENCES CLIENTE (ID)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (IDUSUARIO)
        REFERENCES USUARIO (ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ITEMORCAMENTO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    IDORCAMENTO INT NOT NULL,
    DESCRICAO VARCHAR(200) NOT NULL,
    VALOR DECIMAL(7 , 2 ) DEFAULT 0,
    FOREIGN KEY (IDORCAMENTO)
        REFERENCES ORCAMENTO (ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PROJETO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    IDORCAMENTO INT,
    INICIO DATE,
    PRAZO DATE,
	TITULO VARCHAR(100),
	DESCRICAO VARCHAR(400),
    FINALIZADO BOOL DEFAULT FALSE,
    FOREIGN KEY (IDORCAMENTO)
        REFERENCES ORCAMENTO (ID)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE TAREFA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    IDPROJETO INT NOT NULL,
    FINALIZADA BOOL DEFAULT FALSE,
    ATIVIDADE VARCHAR(300) NOT NULL,
    RELATORIO VARCHAR(300),
    FOREIGN KEY (IDPROJETO)
        REFERENCES PROJETO (ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE NOTA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    IDORCAMENTO INT NOT NULL,
    VALORPAGO DECIMAL(7 , 2 ) NOT NULL,
    DATAEMISSAO DATE,
    FOREIGN KEY (IDORCAMENTO)
        REFERENCES ORCAMENTO (ID)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

























